name: Build and Release VSIX

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.0.1, etc.

permissions:
  contents: write  # Required for creating releases and uploading assets

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package extension
        run: vsce package --no-dependencies

      - name: Get package info
        id: package-info
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          VSIX_FILE="${PACKAGE_NAME}-${PACKAGE_VERSION}.vsix"
          echo "version=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT
          echo "name=${PACKAGE_NAME}" >> $GITHUB_OUTPUT
          echo "vsix-file=${VSIX_FILE}" >> $GITHUB_OUTPUT

      - name: Create Release with VSIX
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          body: |
            ## Sphere Scripter Extension Release ${{ steps.package-info.outputs.version }}
            
            ### Installation
            1. Download the `.vsix` file below
            2. Open VS Code
            3. Press `Ctrl+Shift+P` (or `Cmd+Shift+P` on Mac)
            4. Type "Extensions: Install from VSIX"
            5. Select the downloaded `.vsix` file
            
            ### What's Changed
            See the commit history for detailed changes in this release.
          files: ${{ steps.package-info.outputs.vsix-file }}
          draft: false
          prerelease: false